services:
  ezbookkeeping:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyrilchiu/ezbookkeeping:latest
    container_name: finbook
    networks:
      - finbook-net
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - TZ=UTC
    ports:
      - "8888:8080"
    volumes:
      - ./conf/ezbookkeeping.ini:/ezbookkeeping/conf/ezbookkeeping.ini:ro
      - ./data:/ezbookkeeping/data
      - ./log:/ezbookkeeping/log
      - ./storage:/ezbookkeeping/storage
    restart: unless-stopped

  mysql:
    image: mariadb:11.4
    container_name: finbook-mysql
    networks:
      - finbook-net
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: ezbookkeeping
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_HOST: "%"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} || exit 1"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 12
    ports:
      - "3308:3306"
    restart: unless-stopped

networks:
  finbook-net:
